Added datapack validation check, 2 minute timeout, automatic logs upload on failure

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,8 +2,6 @@ name: GnosiaMC Server Test
 
 on:
   push:
-    branches:
-      - main
   workflow_dispatch:
 
 jobs:
@@ -14,11 +12,12 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up Java 25
-        run: |
-          sudo apt-get update -y --no-install-recommends
-          sudo apt-get install -y openjdk-jdk-25
+        uses: actions/setup-java@v4
+        with:
+          distribution: "temurin"
+          java-version: "25"
 
-      - name: Download 1.21.11 Minecraft
+      - name: Run Server
         run: |
           FLAGS="-XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32"
           mkdir -p /tmp/minecraft/world/datapacks
@@ -26,3 +25,32 @@ jobs:
           cd /tmp/minecraft/
           curl -L -o server.jar "https://fill-data.papermc.io/v1/objects/5ffef465eeeb5f2a3c23a24419d97c51afd7dbb4923ff42df9a3f58bba1ccfba/paper-1.21.11-132.jar"
           echo eula=true > eula.txt
+
+          java $FLAGS -jar server.jar --nogui > server.log 2>&1 &
+          SERVER_PID=$!
+
+          touch server.log
+          if ! timeout 2m tail -f server.log --pid=$SERVER_PID | while read -r line; do
+            echo "$line"
+            if echo "$line" | grep -q "Starting Minecraft server on \*:25565"; then
+              kill $SERVER_PID
+              break
+            fi
+          done; then
+            echo "timeout reached"
+            kill $SERVER_PID 2>/dev/null || true
+            exit 1
+          fi
+
+          if grep -q "Failed to load datapack" server.log || grep -q "Failed to load function" server.log; then
+            echo "Error occurred while loading datapack, uploading artifact of full latest.log"
+            exit 1
+          fi
+
+      - name: Upload Logs Artifact
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: server-logs
+          path: /tmp/minecraft/logs/
+          if-no-files-found: warn
